//Code generated by game config export tool. DO NOT EDIT IT!!!
using System;

namespace CoreBase
{

    [Serializable]
    public class Person1Struct 
    {

		/// <summary>年龄</summary>
		public int Age1 { get; set; }

		/// <summary>一种类型</summary>
		public int Some1 { get; set; }

    

        public void Relate()
        {



        }

    }

}
