//Code generated by game config export tool. DO NOT EDIT IT!!!
using System;

namespace CoreBase
{

    [Serializable]
    public class PersonStruct 
    {

		/// <summary>年龄</summary>
		public int Age { get; set; }

		/// <summary>一种类型</summary>
		public int[] Some { get; set; }

    

        public void Relate()
        {



        }

    }

}
