//Code generated by game config export tool. DO NOT EDIT IT!!!
using System;

namespace CoreBase
{

    [Serializable]
    public class UnitStruct : ITableStruct<uint>
    {

			/// <summary>ID</summary>
		public uint ID { get; set; }

		/// <summary>名称</summary>
		public string Name { get; set; }

		/// <summary>PersonStruct</summary>
		public PersonStruct Person { get; set; }

		/// <summary>3334</summary>
		public int[] DDDD { get; set; }

		/// <summary>Person1Struct</summary>
		public Person1Struct Person1 { get; set; }

		/// <summary>MID->Struct</summary>
		public uint MID { get; set; }

		/// <summary>MapStruct</summary>
		public MapStruct MID2Map { get; set; }

		/// <summary>MID2->Struct</summary>
		public uint[] MID2 { get; set; }

		/// <summary>Map2Struct[]</summary>
		public Map2Struct[] MID22Map2 { get; set; }

    

        public uint GetKey() 
        {
            return ID;
        }

        public void Relate()
        {
	    
	    	MID2Map = Configs.Instance.MapTable[MID];

			MID22Map2 = new Map2Struct[MID2.Length];
			for(int i = 0; i < MID2.Length;++i)
			{
				MID22Map2[i] = Configs.Instance.Map2Table[MID2[i]];
			}

        }

    }

	public partial class Configs : TSingleton<Configs>
	{
        TDataTable<uint,UnitStruct> _UnitTable = TDataTable<uint,UnitStruct>.Instance;

        public TDataTable<uint,UnitStruct> UnitTable => _UnitTable;
	}
}
